name: CrisenpuerEssentials
version: 0.1.0
main: org.eu.pl.crisenpuer.spigot.crisenpuer_essentials.CEssentials
api-version: 1.20.6
commands:
  menu:
    description: Otwórz główne menu serwera
    usage: /menu
  report:
    description: Zgłoś gracza do moderacji serwera. nadużywanie tej komendy spowoduje bana
    usage: /report <nick gracza>